spring.application.name=CinemaBookingService
spring.datasource.url=jdbc:postgresql://localhost:5432/cinema_booking
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
# ==========================================
# JWT Configuration
# ==========================================
jwt.secret=CinemaBookingServiceSecretKeyForJWTAuthentication2026SuperSecureKeyWithEnoughLength
# 30 minutes (in ms)
jwt.access-token-expiration-ms=1800000
# 7 days (in ms)
jwt.refresh-token-expiration-ms=604800000

# ==========================================
# Springdoc / Swagger UI Configuration
# ==========================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
